name: go-write-to-file

on:
  schedule:
    - cron: "25 09 * * *"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Cache dependencies
      id: get-dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Get dependencies
      if: steps.cget-dependencies.outputs.cache-hit != 'true'
      run: go get github.com/shurcooL/githubv4 golang.org/x/oauth2 google.golang.org/api/option

    - name: Build
      run: cd backend && go build -v -o main-to-file main-to-file.go
    
    - run: cd backend && ./main-to-file -gh_token=${{secrets.TOKEN}}

    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time

    - name: push to repo
      env:
        TIME: "${{ steps.current-time.outputs.time }}"
      run: git add backend/data.json && git commit -m "new data at $TIME" && git push
